openapi: 3.0.3
info:
  title: RTCMS4J Notify-service API
  version: 1.0.0
servers:
  - url: /api/v1

security:
  - bearerAuth: [ ]

paths:
  ############################
  # Managing configurations: #
  ############################
  /namespace/{nid}/application/{aid}/sse-stream:
    get:
      tags:
        - Notify
      summary: SSE notifications endpoint
      operationId: subscribeOnNotificationSse
      parameters:
        - name: nid
          description: Namespace id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: aid
          description: Application id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully connected to event stream
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NotificationEventDto"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /namespace/{nid}/application/{aid}/feedback:
    get:
      tags:
        - Notify
      summary: Get application-level feedback
      operationId: getApplicationFeedback
      parameters:
        - name: nid
          description: Namespace id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: aid
          description: Application id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationFeedbackResponseDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Notify
      summary: Post application-level feedback
      operationId: postApplicationFeedback
      parameters:
        - name: nid
          description: Namespace id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: aid
          description: Application id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationFeedbackRequestDto'
      responses:
        '204':
          description: Successfully posted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /namespace/{nid}/application/{aid}/configuration/{cid}/feedback:
    get:
      tags:
        - Notify
      summary: Get configuration-level feedback
      operationId: getConfigurationFeedback
      parameters:
        - name: nid
          description: Namespace id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: aid
          description: Application id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: cid
          description: Configuration id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigurationFeedbackResponseDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Notify
      summary: Post configuration-level feedback
      operationId: postConfigurationFeedback
      parameters:
        - name: nid
          description: Namespace id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: aid
          description: Application id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: cid
          description: Configuration id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigurationFeedbackRequestDto'
      responses:
        '204':
          description: Successfully posted
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Wrong or unexpected
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Wrong token or authorization failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    MethodNotAllowed:
      description: Wrong method
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: Not enough permissions to access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Error on server side
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ErrorResponse:
      type: object
      required:
        - messageCode
        - message
      properties:
        messageCode:
          type: integer
          format: int32
        message:
          type: string

    NotificationEventDto:
      type: object
      required:
        - configurationUpdateEvent
        - passwordRotationEvent
      properties:
        configurationUpdateEvent:
          $ref: '#/components/schemas/ConfigurationUpdateEventDto'
        passwordRotationEvent:
          $ref: '#/components/schemas/PasswordRotationEventDto'

    ConfigurationUpdateEventDto:
      type: object
      required:
        - configurationId
        - content
      properties:
        configurationId:
          type: integer
          format: int64
        content:
          type: string

    PasswordRotationEventDto:
      type: object
      required:
        - newPassword
      properties:
        newPassword:
          type: string

    ApplicationFeedbackRequestDto:
      type: object
      required:
        - clientName
        - isSecretRotated
      properties:
        clientName:
          type: string
        isSecretRotated:
          type: boolean

    ApplicationFeedbackResponseDto:
      type: object
      required:
        - content
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationFeedbackDto'

    ApplicationFeedbackDto:
      type: object
      required:
        - datedAt
        - clientName
        - isSecretRotated
      properties:
        datedAt:
          type: string
          format: datetime
        clientName:
          type: string
        isSecretRotated:
          type: boolean

    ConfigurationFeedbackRequestDto:
      type: object
      required:
        - clientName
        - appliedVersion
      properties:
        clientName:
          type: string
        appliedVersion:
          type: string

    ConfigurationFeedbackResponseDto:
      type: object
      required:
        - content
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ConfigurationFeedbackDto'

    ConfigurationFeedbackDto:
      type: object
      required:
        - datedAt
        - clientName
        - appliedVersion
      properties:
        datedAt:
          type: string
          format: datetime
        clientName:
          type: string
        appliedVersion:
          type: string
